// pages/api/email.js
export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", ["POST"]);
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { intent, recipient, goal, context, details } = req.body || {};

    if (!intent || !recipient || !goal) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    // TODO: plug in your model/provider here.
    // For now, return a simple placeholder so builds never break:
    const draft =
      `To: ${recipient}\n\n` +
      `Intent: ${intent} • Goal: ${goal}\n\n` +
      `Context: ${context || "(none)"}\n` +
      `Details: ${details || "(none)"}\n\n` +
      `-- Generated by MailMate`;

    return res.status(200).json({ ok: true, draft });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: "Internal Server Error" });
  }
}
