export const MODE_LIST = [
  { id: "general", label: "Chat (general)" },
  { id: "mailmate", label: "MailMate (email)" },
  { id: "hirehelper", label: "HireHelper (resume)" },
  { id: "planner", label: "Planner (study/work)" },
];

export const PRESETS_BY_MODE = {
  general: [
    "Summarize",
    "Explain simply",
    "Pros & cons",
    "Action steps",
    "Executive summary",
    "Tighten + verbs",
    "ATS optimization",
    "Case study outline",
    "Interview stories",
  ],
  mailmate: [
    "Reply professionally",
    "Follow-up email",
    "Cold email (networking)",
    "Cold email (sales)",
    "Clarify a misunderstanding",
    "Decline politely",
    "Confirm appointment",
    "Request info",
  ],
  hirehelper: [
    "Tighten resume bullet",
    "Quantify achievement",
    "Reword to action verbs",
    "Write resume summary",
    "Tailor for job description",
    "Highlight leadership",
    "Make ATS-friendly",
    "Reframe career switch",
  ],
  planner: [
    "Task plan",
    "Weekly plan",
    "Study plan",
    "Exam countdown",
    "Project roadmap",
    "Risk register",
    "Daily schedule",
    "Habits plan",
    "Sprint plan",
    "Budget plan",
    "Fitness plan",
    "Reading plan",
    "Morning routine",
    "Travel checklist",
  ],
};
